apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-frontend
  namespace: api-hrm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-frontend
  template:
    metadata:
      labels:
        app: nodejs-frontend
    spec:
      containers:
        - name: nodejs-frontend
          image: princeay0n/nodejs-frontend:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-frontend-service
  namespace: api-hrm
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: nodejs-frontend
