name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.16.1]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install


    - name: Build project
      run: npm run build

    - name: Deploy
      run: echo "Deployment step - add your deployment script here"
      
  trivyScan:
    runs-on: self-hosted
    name: Trivy FS Scan

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trivy FS scan
      run: trivy fs --format table -o fs.html .

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master # Ex: v2.1.0, See the latest version at https://github.com/marketplace/actions/official-sonarqube-scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
       
    
      
  push:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push action
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-hrm:${{github.run_id}}    

    - name : Trivy Image Scan 
      run : trivy image --formate table -o image.html ${{ secrets.DOCKERHUB_USERNAME }}/api-hrm:${{github.run_id}}

